### ISSUE TITLE
Coarse fan resets to theta = 0

### ISSUE THREAD

**Issue by danielcomaduran** [kirtonBCIlab/boccia-bci#66]
For some reason the coarse fan scriptable object sometimes resets theta to be 0 deg.
This is currently fixed when changing the scriptable object value manually, but it should not happen in the first place.

**Comment by anup2ladder** [comment]
Some unexpected behaviour that resulted from [PR#89](https://github.com/kirtonBCIlab/boccia-bci/pull/89) that addressed this issue:

# What works
- [x] CoarseFan scriptable object doesn't reset Theta 0 (i.e. coarse fan no longer disappears)
- [x] Changing _maxCoarseTheta in `FanNamespace.cs` to a new value that is lower than the current does clamp CoarseFanSettings scriptable object to the specified range.

# New unexpected behaviours noted
_Note: As of December 4, 2024_
- If _maxCoarseTheta in FanNamespace.cs is reduced to a lower value (e.g. 120) and then returns it to 170 (as it is now), Theta in CoarseFanSettings scriptable object remains at the previously set lower value (i.e. 120). 
    - In other words, a consequential effect is that the coarse fan settings theta isn't set programmatically anywhere.
    - So if it gets changed, then the only way to modify it is through the Inspector.
    - I don't know if this will cause issues in deployment, if somehow the coarse fan theta gets changed and can't be reverted.
- There's a behaviour where the limits from FanNamespace.cs aren't enforced on the FineFanSettings scriptable objects on load.
    - If _maxFineTheta is changed to a lower value than it was previously set (e.g. 40 instead of the current value of 50), the FineFanSettings scriptable object's Theta value (and thus the generated fine fan) won't respond to the settings. 
    - Theta on FineFanSettings remains at 50 (outside the allowed range). 
    - However, if we stdart interacting with Theta via the GameOptionsMenu (either resetting values to default or moving the rotation range slider), then the limits from FanNamespace.cs are enforced.
